// GENERATED by tools/gen-cities.js from tools/specs.js. Do not edit by hand; change the spec and rebuild.
// Each entry was checked against the live data service by tools/build-city.js.
(function (root) {
  'use strict';
  const CITIES = [
    {
      "id": "chicago-il",
      "name": "Chicago",
      "agency": "Chicago Police Department",
      "type": "socrata",
      "verified": false,
      "bounds": {
        "south": 41.6446,
        "west": -87.9094,
        "north": 42.0287,
        "east": -87.5241
      },
      "portal": "https://data.cityofchicago.org/",
      "datasetPage": "https://data.cityofchicago.org/d/ijzp-q8t2",
      "datasetName": "Crimes - 2001 to Present",
      "domain": "data.cityofchicago.org",
      "dataset": "ijzp-q8t2",
      "timezone": "America/Chicago",
      "when": {
        "field": "date",
        "kind": "floating"
      },
      "fields": {
        "id": "id",
        "lat": "latitude",
        "lon": "longitude",
        "offense": "fbi_code",
        "detail": "description",
        "place": "location_description",
        "area": "block"
      },
      "hosts": [
        "https://data.cityofchicago.org/*"
      ],
      "categoryMap": {
        "06": 6,
        "08B": 8,
        "07": 7,
        "08A": 8,
        "04B": 4,
        "04A": 4,
        "05": 5,
        "03": 3,
        "01A": 1,
        "01B": 1
      },
      "notes": [
        "Chicago publishes reported incidents with the block address, not the exact address. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "seattle-wa",
      "name": "Seattle",
      "agency": "Seattle Police Department",
      "type": "socrata",
      "verified": false,
      "bounds": {
        "south": 47.4933,
        "west": -122.4194,
        "north": 47.7431,
        "east": -122.2481
      },
      "portal": "https://data.seattle.gov/",
      "datasetPage": "https://cos-data.seattle.gov/d/tazs-3rd5",
      "datasetName": "SPD Crime Data: 2008-Present",
      "domain": "cos-data.seattle.gov",
      "dataset": "tazs-3rd5",
      "timezone": "America/Los_Angeles",
      "when": {
        "field": "offense_date",
        "kind": "floating"
      },
      "fields": {
        "id": "offense_id",
        "lat": "latitude",
        "lon": "longitude",
        "cast": "REDACTED",
        "offense": "offense_sub_category",
        "detail": "nibrs_offense_code_description",
        "place": "neighborhood",
        "area": "block_address"
      },
      "hosts": [
        "https://cos-data.seattle.gov/*"
      ],
      "categoryMap": {
        "LARCENY-THEFT": 6,
        "BURGLARY": 5,
        "ASSAULT OFFENSES": 8,
        "MOTOR VEHICLE THEFT": 7,
        "AGGRAVATED ASSAULT": 4,
        "ROBBERY": 3,
        "HOMICIDE": 1
      },
      "notes": [
        "Seattle hides the location of some records (marked REDACTED); those cannot be mapped.",
        "Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "philadelphia-pa",
      "name": "Philadelphia",
      "agency": "Philadelphia Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 39.8763,
        "west": -75.2652,
        "north": 40.1298,
        "east": -74.9498
      },
      "portal": "https://opendataphilly.org/",
      "datasetPage": "https://opendataphilly.org/datasets/crime-incidents/",
      "datasetName": "Crime Incidents",
      "dataUrl": "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/Philadelphia_Crime_Map_WFL1/FeatureServer/0",
      "timezone": "America/New_York",
      "whenKind": "wall",
      "fields": {
        "id": "ID",
        "when": "DISPATCH_DATE_TIME",
        "offense": "UCR_GENERAL",
        "detail": "TEXT_GENERAL_CODE",
        "area": "LOCATION_BLOCK"
      },
      "hosts": [
        "https://services.arcgis.com/*"
      ],
      "categoryMap": {
        "100": 1,
        "300": 3,
        "400": 4,
        "500": 5,
        "600": 6,
        "700": 7
      },
      "notes": [
        "Philadelphia reports incidents by dispatch time and block address. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "charlotte-nc",
      "name": "Charlotte",
      "agency": "Charlotte-Mecklenburg Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 35.0223,
        "west": -81.0192,
        "north": 35.3878,
        "east": -80.636
      },
      "portal": "https://data.charlottenc.gov/",
      "datasetPage": "https://data.charlottenc.gov/",
      "datasetName": "CMPD Incidents",
      "dataUrl": "https://gis.charlottenc.gov/arcgis/rest/services/CMPD/CMPDIncidents/MapServer/0",
      "timezone": "America/New_York",
      "whenKind": "utc",
      "fields": {
        "id": "OBJECTID",
        "when": "DATE_INCIDENT_BEGAN",
        "offense": "HIGHEST_NIBRS_CODE",
        "detail": "HIGHEST_NIBRS_DESCRIPTION",
        "place": "LOCATION_TYPE_DESCRIPTION",
        "area": "LOCATION"
      },
      "hosts": [
        "https://gis.charlottenc.gov/*"
      ],
      "categoryMap": {
        "120": 3,
        "220": 5,
        "240": 7,
        "13B": 8,
        "23H": 6,
        "23F": 6,
        "23C": 6,
        "13A": 4,
        "23G": 6,
        "23D": 6,
        "23A": 6,
        "09A": 1,
        "23B": 6,
        "23E": 6
      },
      "notes": [
        "Charlotte publishes the date of an incident but not the time, so time-of-day filtering is off.",
        "Charlotte lists the most serious offense per incident. Sex crimes are left out so categories match other cities."
      ],
      "timeOfDay": false
    },
    {
      "id": "baltimore-md",
      "name": "Baltimore",
      "agency": "Baltimore Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 39.2167,
        "west": -76.72,
        "north": 39.3815,
        "east": -76.5209
      },
      "portal": "https://data.baltimorecity.gov/",
      "datasetPage": "https://data.baltimorecity.gov/",
      "datasetName": "NIBRS Group A Crime Data",
      "dataUrl": "https://services1.arcgis.com/UWYHeuuJISiGmgXx/arcgis/rest/services/NIBRS_GroupA_Crime_Data/FeatureServer/0",
      "timezone": "America/New_York",
      "whenKind": "utc",
      "fields": {
        "id": "RowID",
        "when": "CrimeDateTime",
        "offense": "CrimeCode",
        "detail": "Description",
        "place": "PremiseType",
        "area": "Location"
      },
      "hosts": [
        "https://services1.arcgis.com/*"
      ],
      "categoryMap": {
        "120": 3,
        "220": 5,
        "240": 7,
        "13B": 8,
        "13A": 4,
        "23F": 6,
        "23H": 6,
        "23C": 6,
        "23G": 6,
        "23D": 6,
        "09A": 1,
        "23B": 6,
        "23A": 6,
        "23E": 6
      },
      "notes": [
        "Victim age, race and gender fields are never loaded. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "boston-ma",
      "name": "Boston",
      "agency": "Boston Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 42.2302,
        "west": -71.1799,
        "north": 42.4005,
        "east": -70.9953
      },
      "portal": "https://data.boston.gov/",
      "datasetPage": "https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system",
      "datasetName": "Crime Incident Reports",
      "dataUrl": "https://services.arcgis.com/sFnw0xNflSi8J0uh/arcgis/rest/services/Boston_Crime_Incidents__App_View/FeatureServer/0",
      "timezone": "America/New_York",
      "whenKind": "utc",
      "fields": {
        "id": "OBJECTID",
        "when": "FROM_DATE",
        "offense": "NIBRS_CODE",
        "detail": "NIBRS_DESC",
        "place": "PREMISE_DESC",
        "area": "BLOCK"
      },
      "hosts": [
        "https://services.arcgis.com/*"
      ],
      "categoryMap": {
        "120": 3,
        "220": 5,
        "240": 7,
        "13B": 8,
        "23C": 6,
        "13A": 4,
        "23H": 6,
        "23D": 6,
        "23F": 6,
        "23G": 6,
        "23A": 6,
        "23B": 6,
        "09A": 1,
        "23E": 6
      },
      "notes": [
        "Boston lists one row per offense in an incident, so one incident can appear more than once. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "raleigh-nc",
      "name": "Raleigh",
      "agency": "Raleigh Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 35.7107,
        "west": -78.8161,
        "north": 35.96,
        "east": -78.4965
      },
      "portal": "https://data.raleighnc.gov/",
      "datasetPage": "https://data.raleighnc.gov/",
      "datasetName": "Raleigh Police Incidents (last 90 days)",
      "dataUrl": "https://services.arcgis.com/v400IkDOw1ad7Yad/arcgis/rest/services/Raleigh_Police_Incidents_Last_90_Days/FeatureServer/0",
      "timezone": "America/New_York",
      "whenKind": "wall",
      "fields": {
        "id": "OBJECTID",
        "when": "reported_date",
        "offense": "crime_category",
        "detail": "crime_description",
        "area": "reported_block_address"
      },
      "hosts": [
        "https://services.arcgis.com/*"
      ],
      "categoryMap": {
        "LARCENY": 6,
        "SIMPLE ASSAULT": 8,
        "LARCENY FROM MV": 6,
        "MV THEFT": 7,
        "AGGRAVATED ASSAULT": 4,
        "BURGLARY/RESIDENTIAL": 5,
        "BURGLARY/COMMERCIAL": 5,
        "ROBBERY": 3,
        "MURDER": 1
      },
      "notes": [
        "Raleigh publishes the last 90 days only, by the time the incident was reported. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "las-vegas-nv",
      "name": "Las Vegas",
      "agency": "Las Vegas Metropolitan Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 35.1507,
        "west": -116.01,
        "north": 37.0099,
        "east": -114.5648
      },
      "portal": "https://opendata-lvmpd.hub.arcgis.com/",
      "datasetPage": "https://opendata-lvmpd.hub.arcgis.com/",
      "datasetName": "Reported NIBRS Crime",
      "dataUrl": "https://services.arcgis.com/jjSk6t82vIntwDbs/arcgis/rest/services/Weekly_Public_Crimes/FeatureServer/0",
      "timezone": "America/Los_Angeles",
      "whenKind": "utc",
      "fields": {
        "id": "OBJECTID",
        "when": "ReportedOn",
        "offense": "NIBRSOffenseCode",
        "detail": "Offense",
        "place": "LocationType",
        "area": "Location"
      },
      "hosts": [
        "https://services.arcgis.com/*"
      ],
      "categoryMap": {
        "120": 3,
        "220": 5,
        "240": 7,
        "13B": 8,
        "23H": 6,
        "23C": 6,
        "23F": 6,
        "13A": 4,
        "23D": 6,
        "23G": 6,
        "23A": 6,
        "23B": 6,
        "09A": 1,
        "23E": 6
      },
      "notes": [
        "This is the Las Vegas Metropolitan Police Department, which also covers unincorporated Clark County. Times are when the incident was reported. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "fort-worth-tx",
      "name": "Fort Worth",
      "agency": "Fort Worth Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 32.5636,
        "west": -97.5158,
        "north": 33.0338,
        "east": -97.0457
      },
      "portal": "https://data.fortworthtexas.gov/",
      "datasetPage": "https://data.fortworthtexas.gov/",
      "datasetName": "Crime Data",
      "dataUrl": "https://mapit.fortworthtexas.gov/ags/rest/services/CIVIC/Crime_Data/MapServer/0",
      "timezone": "America/Chicago",
      "whenKind": "wall",
      "fields": {
        "id": "OBJECTID",
        "when": "From_Date",
        "offense": "Offense",
        "detail": "Offense_Desc",
        "place": "LocationTypeDescription",
        "area": "BLOCK_ADDRESS"
      },
      "hosts": [
        "https://mapit.fortworthtexas.gov/*"
      ],
      "categoryMap": {
        "120": 3,
        "220": 5,
        "240": 7,
        "23H": 6,
        "13B": 8,
        "23F": 6,
        "23C": 6,
        "13A": 4,
        "23G": 6,
        "23B": 6,
        "23D": 6,
        "09A": 1,
        "23A": 6,
        "23E": 6
      },
      "notes": [
        "Some Fort Worth records carry only a date, so they show as midnight. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "long-beach-ca",
      "name": "Long Beach",
      "agency": "Long Beach Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 33.741,
        "west": -118.2322,
        "north": 33.8913,
        "east": -118.0678
      },
      "portal": "https://data.longbeach.gov/",
      "datasetPage": "https://data.longbeach.gov/",
      "datasetName": "Police Crime Mapping",
      "dataUrl": "https://services6.arcgis.com/yCArG7wGXGyWLqav/arcgis/rest/services/Police_Crime_Mapping/FeatureServer/0",
      "timezone": "America/Los_Angeles",
      "whenKind": "utc",
      "fields": {
        "id": "OBJECTID",
        "when": "ReportedDateTimeDate",
        "offense": "CrimeType",
        "detail": "CrimeType",
        "area": "Address"
      },
      "hosts": [
        "https://services6.arcgis.com/*"
      ],
      "categoryMap": {
        "SIMPLE ASSAULT": 8,
        "MOTOR VEHICLE THEFT": 7,
        "AGGRAVATED ASSAULT": 4,
        "BURGLARY/BREAKING AND ENTERING": 5,
        "SHOPLIFTING": 6,
        "THEFT OF MOTOR VEHICLE PARTS OR ACCESSORIES": 6,
        "THEFT FROM MOTOR VEHICLE": 6,
        "ALL OTHER LARCENY": 6,
        "ROBBERY": 3,
        "THEFT FROM BUILDINGS": 6,
        "PURSE SNATCHING": 6,
        "POCKET PICKING": 6,
        "MURDER & NON-NEGLIGENT MANSLAUGHTER": 1,
        "MANSLAUGHTER BY NEGLIGENCE": 1
      },
      "notes": [
        "Long Beach publishes recent reports by the time they were reported. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "detroit-mi",
      "name": "Detroit",
      "agency": "Detroit Police Department",
      "type": "arcgis",
      "verified": false,
      "bounds": {
        "south": 42.2585,
        "west": -83.2936,
        "north": 42.4591,
        "east": -82.909
      },
      "portal": "https://data.detroitmi.gov/",
      "datasetPage": "https://data.detroitmi.gov/",
      "datasetName": "RMS Crime Incidents",
      "dataUrl": "https://services2.arcgis.com/qvkbeam7Wirps6zC/arcgis/rest/services/RMS_Crime_Incidents/FeatureServer/0",
      "timezone": "America/New_York",
      "whenKind": "utc",
      "fields": {
        "id": "ESRI_OID",
        "when": "incident_occurred_at",
        "offense": "offense_category",
        "detail": "offense_description",
        "area": "nearest_intersection"
      },
      "hosts": [
        "https://services2.arcgis.com/*"
      ],
      "categoryMap": {
        "ASSAULT": 8,
        "LARCENY": 6,
        "AGGRAVATED ASSAULT": 4,
        "STOLEN VEHICLE": 7,
        "BURGLARY": 5,
        "ROBBERY": 3,
        "HOMICIDE": 1,
        "JUSTIFIABLE HOMICIDE": 1
      },
      "notes": [
        "Detroit lists one row per offense, so one incident can appear more than once. Sex crimes are left out so categories match other cities."
      ]
    }
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = CITIES;
  else { root.RunSafe = root.RunSafe || {}; root.RunSafe.cities = CITIES; }
})(typeof self !== 'undefined' ? self : this);
