// GENERATED by tools/gen-cities.js from tools/specs.js. Do not edit by hand; change the spec and rebuild.
// Each entry was checked against the live data service by tools/build-city.js.
(function (root) {
  'use strict';
  const CITIES = [
    {
      "id": "chicago-il",
      "name": "Chicago",
      "agency": "Chicago Police Department",
      "type": "socrata",
      "verified": false,
      "bounds": {
        "south": 41.6446,
        "west": -87.9094,
        "north": 42.0287,
        "east": -87.5241
      },
      "portal": "https://data.cityofchicago.org/",
      "datasetPage": "https://data.cityofchicago.org/d/ijzp-q8t2",
      "datasetName": "Crimes - 2001 to Present",
      "domain": "data.cityofchicago.org",
      "dataset": "ijzp-q8t2",
      "timezone": "America/Chicago",
      "when": {
        "field": "date",
        "kind": "floating"
      },
      "fields": {
        "id": "id",
        "lat": "latitude",
        "lon": "longitude",
        "offense": "fbi_code",
        "detail": "description",
        "place": "location_description",
        "area": "block"
      },
      "hosts": [
        "https://data.cityofchicago.org/*"
      ],
      "categoryMap": {
        "06": 6,
        "08B": 8,
        "07": 7,
        "08A": 8,
        "04B": 4,
        "04A": 4,
        "05": 5,
        "03": 3,
        "01A": 1,
        "01B": 1
      },
      "notes": [
        "Chicago publishes reported incidents with the block address, not the exact address. Sex crimes are left out so categories match other cities."
      ]
    },
    {
      "id": "seattle-wa",
      "name": "Seattle",
      "agency": "Seattle Police Department",
      "type": "socrata",
      "verified": false,
      "bounds": {
        "south": 47.4933,
        "west": -122.4194,
        "north": 47.7431,
        "east": -122.2481
      },
      "portal": "https://data.seattle.gov/",
      "datasetPage": "https://cos-data.seattle.gov/d/tazs-3rd5",
      "datasetName": "SPD Crime Data: 2008-Present",
      "domain": "cos-data.seattle.gov",
      "dataset": "tazs-3rd5",
      "timezone": "America/Los_Angeles",
      "when": {
        "field": "offense_date",
        "kind": "floating"
      },
      "fields": {
        "id": "offense_id",
        "lat": "latitude",
        "lon": "longitude",
        "cast": "REDACTED",
        "offense": "offense_sub_category",
        "detail": "nibrs_offense_code_description",
        "place": "neighborhood",
        "area": "block_address"
      },
      "hosts": [
        "https://cos-data.seattle.gov/*"
      ],
      "categoryMap": {
        "LARCENY-THEFT": 6,
        "BURGLARY": 5,
        "ASSAULT OFFENSES": 8,
        "MOTOR VEHICLE THEFT": 7,
        "AGGRAVATED ASSAULT": 4,
        "ROBBERY": 3,
        "HOMICIDE": 1
      },
      "notes": [
        "Seattle hides the location of some records (marked REDACTED); those cannot be mapped.",
        "Sex crimes are left out so categories match other cities."
      ]
    }
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = CITIES;
  else { root.RunSafe = root.RunSafe || {}; root.RunSafe.cities = CITIES; }
})(typeof self !== 'undefined' ? self : this);
