// Writes lib/cities.js from tools/specs.js plus the validated results in tools/out/*.json.
// Only cities whose build-city.js run passed every check are included.
//   node tools/gen-cities.js
const fs = require('fs');
const path = require('path');
const specs = require('./specs.js');

const arcSpecs = require('./specs-arcgis.js');
const entries = [];
const skipped = [];
const readOut = (id) => { const f = path.join(__dirname, 'out', id + '.json'); return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : null; };

for (const spec of specs) {
  const out = readOut(spec.id);
  if (!out || !out.ok) { skipped.push(spec.id); continue; }
  const c = spec.config;
  entries.push({
    id: spec.id, name: c.name, agency: c.agency, type: 'socrata', verified: false,
    bounds: out.bounds, portal: c.portal, datasetPage: c.datasetPage, datasetName: c.datasetName,
    domain: c.domain, dataset: c.dataset, timezone: c.timezone, when: c.when, fields: c.fields,
    hosts: ['https://' + c.domain + '/*'], categoryMap: out.categoryMap, notes: spec.notes || [],
  });
}
for (const spec of arcSpecs) {
  const out = readOut(spec.id);
  if (!out || !out.ok) { skipped.push(spec.id); continue; }
  const c = spec.config;
  const e = {
    id: spec.id, name: c.name, agency: c.agency, type: 'arcgis', verified: false,
    bounds: out.bounds, portal: c.portal, datasetPage: c.datasetPage, datasetName: c.datasetName,
    dataUrl: spec.dataUrl, timezone: c.timezone, whenKind: out.whenKind, fields: c.fields,
    hosts: [new URL(spec.dataUrl).origin + '/*'], categoryMap: out.categoryMap, notes: spec.notes || [],
  };
  if (out.timeOfDay === false) e.timeOfDay = false;
  entries.push(e);
}
const body = "// GENERATED by tools/gen-cities.js from tools/specs.js. Do not edit by hand; change the spec and rebuild.\n" +
  "// Each entry was checked against the live data service by tools/build-city.js.\n" +
  "(function (root) {\n  'use strict';\n  const CITIES = " + JSON.stringify(entries, null, 2).replace(/\n/g, '\n  ') + ";\n" +
  "  if (typeof module !== 'undefined' && module.exports) module.exports = CITIES;\n  else { root.RunSafe = root.RunSafe || {}; root.RunSafe.cities = CITIES; }\n" +
  "})(typeof self !== 'undefined' ? self : this);\n";
fs.writeFileSync(path.join(__dirname, '..', 'lib', 'cities.js'), body);
console.log('wrote lib/cities.js with', entries.map((e) => e.id).join(', '), skipped.length ? '| skipped (not validated): ' + skipped.join(', ') : '');
